_posts/0000-01-17-TerHano.md
Updated TerHano's markdown file to fix #28.
=> Altered TerHano markdown file

_posts/0000-01-10-RonkasPSEG.md
This is a change to the '_post', 'RonkasPSEG' file. It updates the caption to be more in line with the provided image
closes
Fixes #23 
Resolves
=> Update caption based on provided image for RonkasPSEG file.

_posts/0000-01-07-NowshadAzimi.md
Fixes the issue with caption.
Fixes #29
=> Nowshad azimi - Ch123 Update on caption image

_posts/0000-01-06-a00125970.md
=> Update caption based on provided image

_posts/0000-01-21-Mike-the-powerful.md
=> update caption per my IMAGE

_posts/0000-01-23-beardofedu.md
This is a change to the `_posts`, `beardofedu` file. It updates the caption to be more inline with the provided image. 
Closes 
Fixes #14 
Resolves
=> CHG-123: Update caption for beardofedu file

_posts/0000-01-14-derekacevedo.md
This is a change to the '_posts', 'derekacevedo' file. It updates the caption to be more inline with the provided image.
Closes #27
=> Updating caption based on picture provided.

_posts/0000-01-13-MatthewSchlosserPSEG.md
This is an update in the "_posts"."MatthewSchlosserPSEG" file. It updates the caption to be more accurate
Closes
Fixes #24 
Resolves
=> Updated caption based on provided image

_posts/0000-01-09-chinrung.md
=> CHG-111: update the markdown

_posts/0000-01-15-Shdesai36.md
=> Update caption based on provided imange

_posts/0000-01-19-awhite575.md
Update caption based on provided image
closes
fixes #34 
resolves
=> CHG-123 Update caption based on provided image

_posts/0000-01-18-arch02.md
=> Update caption on image

_posts/0000-01-11-designMoreWeb.md
Committed the change for octocat comment
=> Design moreweb comment

_posts/0000-01-12-Gymky.md
This was a change to the '_post' file, it update the caption to be more inline with the image provided.
closes #5
=> CHG11111: Update to Gymky caption file

_posts/0000-01-08-wsmith2.md, _posts/0000-01-20-wsmith2.md
Modify the files to update the push
Closes #25
=> CHG7823: Update the text in the slide decks

_posts/0000-01-02-satyapenta.md
My Changes
Closes #41 
Fixes #41 
Resolved #41
=> Updated Caption on Provided Image

README.md, _posts/0000-03-10-peterhugger.md
Added a new slide for the deck using the new 'feature' > 'develop' > 'master' > workflow
=> Added new blank slide for PeterHugger

README.md, _posts/0000-03-10-MatthewSchlosserPSEG.md
Adding a new slide for the image deck
=> MatthewSchlosserPSEG add a new slide for dev branch testing

README.md, _posts/0000-01-05-BinduTuli0609.md, _posts/0000-01-24-BinduTuli0609.md
lets see if we can resolve this merge conflict.
=> Bindu tuli0609 new

README.md, _posts/0000-03-10-MIKE.md
=> MIKE ADDING a new slide for deck

README.md, _posts/0000-01-18-arch02_new.md
Adding a new slide for our deck using new feature .
=> arch02: Add new slide for dev branch testing

README.md, _posts/0000-03-10-TerHano.md
Added a new slide with sake octo-cat.
=> Added a new slide for TerHano to merge into develop

README.md, _posts/0000-02-01-a00125970.md
Adding a new slide for our deck using the new deck
=> Ebb: Add new slide for dev branch testing

README.md, _posts/0000-03-99-wsmith2.md
added a new slide for will smith
=> Wsmith2 slide

README.md, _posts/0000-02-01-derekacevedo.md
=> Add a new slide for derekacevedo

README.md, _posts/0000-03-10-RonkasPSEG.md
Add new slide for for our deck using new feature > develop > master Workflow
=> RonkasPSEG: Add new slide for dev branch testing

README.md, _posts/0000-01-24-awhite575.md, imnew.md
=> Awhite575 slide
